<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDx56vml\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDx56vml/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerDx56vml.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerDx56vml\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerDx56vml\appProdProjectContainer([
    'container.build_hash' => 'Dx56vml',
    'container.build_id' => '0d5a3ac8',
    'container.build_time' => 1689407538,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDx56vml');
